name = "markdownbox"
main = "src/worker.ts"
compatibility_date = "2026-05-20"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "USERS_KV"
id = "97e5a17ecf744f96b492337f7dfa27aa"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "81a2811cb3df42059c81e3fb82ec1b32"

[[kv_namespaces]]
binding = "DOCS_KV"
id = "ae43f100757f4f25ba093a9efa247a39"

[[kv_namespaces]]
binding = "SHARES_KV"
id = "f532dea7acc444c9a62f1e7023a2a687"

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "markdown-box-077f5b1a"

[vars]
SESSION_TTL_SECONDS = "259200"
